/********************************* 
    TIMER Configuration File   
*********************************/ 
 
#ifndef TIMER0_CFG_H 
#define TIMER0_CFG_H 

 #include "TIMER0_piv.h"
 
/********** Prescaler configuration **********/
/*  TMR0_CLK_NO_SOURCE
    TMR0_CLK_PRESCALER_1
    TMR0_CLK_PRESCALER_8
    TMR0_CLK_PRESCALER_64
    TMR0_CLK_PRESCALER_256
    TMR0_CLK_PRESCALER_1024
    TMR0_CLK_EXT_FALLING_EDGE
    TMR0_CLK_EXT_RISING_EDGE    */
#define TMR0_PRESCALER TMR0_CLK_PRESCALER_8
 
/************ Mode configuration ************/
/*   TMR0_MODE_NORMAL_DISCONNECT_OC0
     TMR0_MODE_NORMAL_TOGGLE_OC0_CM
     TMR0_MODE_NORMAL_CLEAR_OC0_CM
     TMR0_MODE_NORMAL_SET_OC0_CM
     TMR0_MODE_CTC_DISCONNECT_OC0
     TMR0_MODE_CTC_TOGGLE_OC0_CM
     TMR0_MODE_CTC_CLEAR_OC0_CM
     TMR0_MODE_CTC_SET_OC0_CM
     TMR0_MODE_PWM_DISCONNECTED_OC0
     TMR0_MODE_PWM_NON_INVERTING
     TMR0_MODE_PWM_INVERTING
     TMR0_MODE_FAST_PWM_DISCONNECTED_OC0
     TMR0_MODE_FAST_PWM_NON_INVERTING
     TMR0_MODE_FAST_PWM_INVERTING          */
#define TMR0_MODE TMR0_MODE_FAST_PWM_NON_INVERTING

/************ Interrupt Enable ***************/
 /*     TMR0_INT_ENABLE 
        TMR0_INT_DISABLE          */
 #define TMR0_INTERRUPT_CM_ENABLE TMR0_INT_ENABLE
 #define TMR0_INTERRUPT_OV_ENABLE TMR0_INT_ENABLE
 
#endif /*TIMER0_CFG_H*/ 
