#include "Std_types.h" 
#include "Bit_math.h"  
#include "EXTERNAL_INTERRUPT.h" 
#include "EXTERNAL_INTERRUPT_cfg.h" 
#include "EXTERNAL_INTERRUPT_piv.h" 

/* external interrupt function implementation */
EXTERNAL_INTERRUPT_tenuErrorStatus EXTERNAL_INTERRUPT_enuInit(void)
{
	/********************************* for INT0 ***********************************/
	#if EXTERNAL_INTERRUPT_0 == EXTERNAL_INTERRUPT_0_ENABLED
	
		SET_BIT(EXTERNAL_INTERRUPT_GICR_REGISTER , EXTERNAL_INTERRUPT_GICR_INT0pin); // set bit 6 to enable general interrupt for INT0
		
		#if EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_RISING_EDGE_MODE
			u8 Loc_u8Temp0 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp0 &= (~ EXTERNAL_INTERRUPT_CLR_MASK);
			Loc_u8Temp0 |= EXTERNAL_INTERRUPT_01_RISING_EDGE_MODE;
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp0;
		
		#elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_FALLING_EDGE_MODE
			u8 Loc_u8Temp0 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp0 &= (~ EXTERNAL_INTERRUPT_CLR_MASK);
			Loc_u8Temp0 |= EXTERNAL_INTERRUPT_01_FALLING_EDGE_MODE;
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp0;
		
		#elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_LOGICAL_CHANGE_MODE
			u8 Loc_u8Temp0 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp0 &= (~ EXTERNAL_INTERRUPT_CLR_MASK);
			Loc_u8Temp0 |= EXTERNAL_INTERRUPT_01_LOGICAL_CHANGE_MODE;
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp0;
		
		#elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_LOW_LEVEL_MODE
			u8 Loc_u8Temp0 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp0 &= (~ EXTERNAL_INTERRUPT_CLR_MASK);
			Loc_u8Temp0 |= EXTERNAL_INTERRUPT_01_LOW_LEVEL_MODE;
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp0;
		
		#endif
	
	#endif	
	/********************************* for INT1 ***********************************/
	#if EXTERNAL_INTERRUPT_1 == EXTERNAL_INTERRUPT_1_ENABLED
	
		SET_BIT(EXTERNAL_INTERRUPT_GICR_REGISTER , EXTERNAL_INTERRUPT_GICR_INT1pin); // set bit 7 to enable general interrupt for INT1
	    
	    #if EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_RISING_EDGE_MODE
			u8 Loc_u8Temp1 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp1 &= (~ (EXTERNAL_INTERRUPT_CLR_MASK << 2));
			Loc_u8Temp1 |= (EXTERNAL_INTERRUPT_01_RISING_EDGE_MODE << 2);
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp1;
	    
	    #elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_FALLING_EDGE_MODE
			u8 Loc_u8Temp1 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp1 &= (~ (EXTERNAL_INTERRUPT_CLR_MASK << 2));
			Loc_u8Temp1 |= ( EXTERNAL_INTERRUPT_01_FALLING_EDGE_MODE << 2);
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp1;
	    
	    #elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_LOGICAL_CHANGE_MODE
			u8 Loc_u8Temp1 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp1 &= (~ (EXTERNAL_INTERRUPT_CLR_MASK << 2));
			Loc_u8Temp1 |= (EXTERNAL_INTERRUPT_01_LOGICAL_CHANGE_MODE << 2);
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp1;
	    
	    #elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_01_LOW_LEVEL_MODE
			u8 Loc_u8Temp1 = EXTERNAL_INTERRUPT_MCUCR_REGISTER;
			Loc_u8Temp1 &= (~ (EXTERNAL_INTERRUPT_CLR_MASK << 2));
			Loc_u8Temp1 |= (EXTERNAL_INTERRUPT_01_LOW_LEVEL_MODE << 2); 
			EXTERNAL_INTERRUPT_MCUCR_REGISTER = Loc_u8Temp1;
	    
	    #endif
	#endif
	/********************************* for INT2 ***********************************/
	#if EXTERNAL_INTERRUPT_2 == EXTERNAL_INTERRUPT_2_ENABLED
	
		SET_BIT(EXTERNAL_INTERRUPT_GICR_REGISTER , EXTERNAL_INTERRUPT_GICR_INT2pin); // set bit 5 to enable general interrupt for INT2
		
		#if EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_2_RISING_EDGE_MODE
			SET_BIT(EXTERNAL_INTERRUPT_MCUCSR_REGISTER , EXTERNAL_INTERRUPT_MCUCSR_ISC2pin); // set bit 6 to choose rising edge for INT2
		
		#elif EXTERNAL_INTERRUPT_MODE == EXTERNAL_INTERRUPT_2_FALLING_EDGE_MODE
			CLR_BIT(EXTERNAL_INTERRUPT_MCUCSR_REGISTER , EXTERNAL_INTERRUPT_MCUCSR_ISC2pin); // clear bit 6 to choose rising edge for INT2
		
		#endif
		
	#endif	
	
	return EXTERNAL_INTERRUPT_enuOk;
}