/********************************* 
    ADC Configuration File   
*********************************/ 
 
#ifndef ADC_CFG_H 
#define ADC_CFG_H 
 
 #define ADC_10_BITS 0
 #define ADC_8_BITS 1
 
 /* ADC_VOLTREF_AREF 
    ADC_VOLTREF_AVCC 
    ADC_VOLTREF_INTERNAL */
 #define ADC_VOLTAGE_REFERENCE ADC_VOLTREF_AVCC
 
 /* ADC_PRESCALER_2  
 	ADC_PRESCALER_4  
 	ADC_PRESCALER_8  
 	ADC_PRESCALER_16 
 	ADC_PRESCALER_32 
 	ADC_PRESCALER_64 
 	ADC_PRESCALER_128 */
 #define ADC_PRESCALER ADC_PRESCALER_128
 
 /* ADC_STATUS_ENABLE 
 	ADC_STATUS_DISABLE */
 #define ADC_STATUS ADC_STATUS_ENABLE
 
 /* ADC_10_BITS
    ADC_8_BITS */
 #define ADC_BITS ADC_8_BITS
 
 /* ADC_LEFTADJUST_ENABLE 
 	ADC_LEFTADJUST_DISABLE */
 #define ADC_LEFT_ADJUST ADC_LEFTADJUST_ENABLE
 
 /* ADC_INTERRUPT_ENABLE 
    ADC_INTERRUPT_DISABLE */
 #define ADC_INTERRUPT_STATUS ADC_INTERRUPT_DISABLE
 
 /* ADC_AUTOTRIGGER_ENABLE 
 	ADC_AUTOTRIGGER_DISABLE */
 #define ADC_AUTO_TRIGGER_STATUS ADC_AUTOTRIGGER_ENABLE
 
#endif /*ADC_CFG_H*/ 
